// Purpose: Format and generate morning markdown reports of research runs.
// Docs: report.doc.md

package alchemist

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"
	"time"
)

// MorningReport is the summary generated at end of overnight run
type MorningReport struct {
	StartTime   time.Time
	EndTime     time.Time
	Duration    time.Duration
	WorkBranch  string
	Summary     map[string]any
	Experiments []ExperimentRecord
	Learnings   []string
	TopCommits  []ExperimentRecord
	DiffPreview string
	ProgramFile string
}

// generateMorningReport builds the final report
func (d *Daemon) generateMorningReport() (*MorningReport, error) {
	summary, err := d.history.Summary()
	if err != nil {
		return nil, err
	}

	experiments, err := d.history.Recent(50)
	if err != nil {
		return nil, err
	}

	// Filter committed experiments for "top commits"
	var topCommits []ExperimentRecord
	for _, e := range experiments {
		if e.Decision == "committed" {
			topCommits = append(topCommits, e)
			if len(topCommits) >= 10 {
				break
			}
		}
	}

	// Diff preview
	diff, _ := d.git.Diff(context.Background())
	if len(diff) > 3000 {
		diff = diff[:3000] + "\n\n[... diff truncated ...]"
	}

	return &MorningReport{
		StartTime:   d.startTime,
		EndTime:     time.Now(),
		Duration:    time.Since(d.startTime),
		WorkBranch:  d.cfg.WorkBranch,
		Summary:     summary,
		Experiments: experiments,
		Learnings:   d.program.Learnings(),
		TopCommits:  topCommits,
		DiffPreview: diff,
		ProgramFile: d.cfg.ProgramFile,
	}, nil
}

// RenderMarkdown formats the report as Markdown
func (r *MorningReport) RenderMarkdown() (string, error) {
	tmpl := `# 🧪 Alchemist Morning Report

**Run:** {{.StartTime.Format "2006-01-02 15:04"}} → {{.EndTime.Format "15:04"}} ({{.Duration.Round time.Second}})
**Branch:** ` + "`{{.WorkBranch}}`" + `
**Program:** ` + "`{{.ProgramFile}}`" + `

## 📊 Summary

| Metric | Value |
|---|---|
| Total experiments | {{index .Summary "total_experiments"}} |
| ✅ Committed | {{index .Summary "committed"}} |
| ❌ Discarded | {{index .Summary "discarded"}} |
| ⚠️ Errors/Timeouts | {{index .Summary "errors"}} |
| Success rate | {{printf "%.1f" (mult (index .Summary "success_rate") 100.0)}}% |
| Best improvement | {{printf "%.4f" (index .Summary "best_delta")}} |
| Total compute | {{index .Summary "total_runtime"}} |

## 🏆 Top Improvements

{{if .TopCommits}}| # | Hypothesis | Metric Δ | Commit |
|---|---|---|---|
{{range $i, $c := .TopCommits}}| {{inc $i}} | {{$c.Hypothesis}} | {{printf "%+.4f" $c.Delta}} | ` + "`{{$c.CommitSHA}}`" + ` |
{{end}}{{else}}_No successful commits this run._
{{end}}

## 📚 Learnings (written to program.md)

{{if .Learnings}}{{range .Learnings}}- {{.}}
{{end}}{{else}}_No learnings recorded._
{{end}}

## 📝 Recent Experiments (last 15)

{{range .RecentN 15}}- **[{{.Decision}}]** {{.Hypothesis}} (metric: {{printf "%.4f" .MetricAfter}}, Δ={{printf "%+.4f" .Delta}})
{{end}}

## 🔍 Git Diff Preview

` + "```diff" + `
{{.DiffPreview}}
` + "```" + `

---
_Generated by sin-code alchemist · Branch is LOCAL ONLY (never pushed automatically)._
_Review and push manually: ` + "`git push -u origin {{.WorkBranch}}`" + `_
`

	funcMap := template.FuncMap{
		"inc": func(i int) int { return i + 1 },
		"mult": func(a, b any) float64 {
			af := toFloat(a)
			bf := toFloat(b)
			return af * bf
		},
	}

	t, err := template.New("report").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		// Fallback to simple rendering if the template itself cannot be parsed.
		return r.renderSimple(), nil
	}

	// Simpler approach: render without template helpers that need methods
	var buf bytes.Buffer
	if err := t.Execute(&buf, r); err != nil {
		// Fallback to simple rendering
		return r.renderSimple(), nil
	}
	return buf.String(), nil
}

// RecentN is a template helper
func (r *MorningReport) RecentN(n int) []ExperimentRecord {
	if n > len(r.Experiments) {
		return r.Experiments
	}
	return r.Experiments[:n]
}

// renderSimple is a fallback that doesn't use templates
func (r *MorningReport) renderSimple() string {
	var sb strings.Builder

	sb.WriteString("# 🧪 Alchemist Morning Report\n\n")
	fmt.Fprintf(&sb, "**Run:** %s → %s (%s)\n",
		r.StartTime.Format("2006-01-02 15:04"),
		r.EndTime.Format("15:04"),
		r.Duration.Round(time.Second))
	fmt.Fprintf(&sb, "**Branch:** `%s`\n", r.WorkBranch)
	fmt.Fprintf(&sb, "**Program:** `%s`\n\n", r.ProgramFile)

	sb.WriteString("## 📊 Summary\n\n")
	fmt.Fprintf(&sb, "- Total experiments: %v\n", r.Summary["total_experiments"])
	fmt.Fprintf(&sb, "- ✅ Committed: %v\n", r.Summary["committed"])
	fmt.Fprintf(&sb, "- ❌ Discarded: %v\n", r.Summary["discarded"])
	fmt.Fprintf(&sb, "- ⚠️  Errors: %v\n", r.Summary["errors"])
	fmt.Fprintf(&sb, "- Success rate: %.1f%%\n", toFloat(r.Summary["success_rate"])*100)
	fmt.Fprintf(&sb, "- Best improvement: %.4f\n", toFloat(r.Summary["best_delta"]))
	fmt.Fprintf(&sb, "- Total compute: %v\n\n", r.Summary["total_runtime"])

	sb.WriteString("## 🏆 Top Improvements\n\n")
	if len(r.TopCommits) > 0 {
		sb.WriteString("| # | Hypothesis | Metric Δ | Commit |\n")
		sb.WriteString("|---|---|---|---|\n")
		for i, c := range r.TopCommits {
			fmt.Fprintf(&sb, "| %d | %s | %+.4f | `%s` |\n",
				i+1, c.Hypothesis, c.Delta, shortSHA(c.CommitSHA))
		}
	} else {
		sb.WriteString("_No successful commits this run._\n")
	}
	sb.WriteString("\n")

	sb.WriteString("## 📚 Learnings (written to program.md)\n\n")
	if len(r.Learnings) > 0 {
		for _, l := range r.Learnings {
			fmt.Fprintf(&sb, "- %s\n", l)
		}
	} else {
		sb.WriteString("_No learnings recorded._\n")
	}
	sb.WriteString("\n")

	sb.WriteString("## 📝 Recent Experiments\n\n")
	recent := r.Experiments
	if len(recent) > 15 {
		recent = recent[:15]
	}
	for _, e := range recent {
		fmt.Fprintf(&sb, "- **[%s]** %s (metric=%.4f, Δ=%+.4f)\n",
			e.Decision, e.Hypothesis, e.MetricAfter, e.Delta)
	}
	sb.WriteString("\n")

	sb.WriteString("## 🔍 Git Diff Preview\n\n```diff\n")
	sb.WriteString(r.DiffPreview)
	sb.WriteString("\n```\n\n---\n")
	sb.WriteString("_Branch is LOCAL ONLY (never pushed automatically)._\n")
	fmt.Fprintf(&sb, "_Push manually: `git push -u origin %s`_\n", r.WorkBranch)

	return sb.String()
}

func toFloat(v any) float64 {
	switch x := v.(type) {
	case float64:
		return x
	case float32:
		return float64(x)
	case int:
		return float64(x)
	case int64:
		return float64(x)
	default:
		return 0
	}
}

func shortSHA(sha string) string {
	if len(sha) > 7 {
		return sha[:7]
	}
	return sha
}
